---
name: Publish release image
inputs:
  registry:
    type: string
    description: Container Registry
  organization:
    type: string
    description: Organization
  login:
    type: string
    description: Username
  password:
    type: string
    description: Password
  container_image_name:
    description: Name of the container image
    type: string
  container_image_tag:
    description: Container image tag
    type: string
    default: ${{ github.ref_name }}
  container_image_arch:
    description: Container image architecture
    type: string
    default: "linux/amd64"
runs:
  using: composite
  steps:

    - name: Login to ${{ inputs.registry }} Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.login }}
        password: ${{ inputs.password }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        no-cache: true
        platforms: ${{ inputs.container_image_arch }}
        push: true
        sbom: true
        tags: 
          - ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.container_image_name }}:${{ inputs.container_image_tag }}
          - ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.container_image_name }}:latest
