---
name: Publish image
inputs:
  image_name:
    type: string
    description: Name of the container image
  image_arch:
    type: string
    description: Container image architecture
  docker_hub_organization:
    type: string
    description: DockerHub organization
    default: prom
  docker_hub_login:
    type: string
    description: DockerHub username
  docker_hub_password:
    type: string
    description: DockerHub password
  quay_io_organization:
    type: string
    description: Quay.io organization
    default: prometheus
  quay_io_login:
    type: string
    description: Quay.io username
  quay_io_password:
    type: string
    description: Quay.io password
runs:
  using: composite
  steps:

    - name: Setup Environment
      uses: ./.github/promci/actions/setup_environment
      with:
        enable_docker_multibuild: true

    - name: Restore Artifacts
      uses: ./.github/promci/actions/restore_artifacts

    - name: Run Publish Container
      uses: ./.github/promci/actions/publish_main_images
      if: inputs.docker_hub_organization != '' && inputs.docker_hub_login != ''
      with:
        registry: docker.io
        organization: ${{ inputs.docker_hub_organization }}
        login: ${{ inputs.docker_hub_login }}
        password: ${{ inputs.docker_hub_password }}
        container_image_name: ${{ inputs.image_name }}
        container_image_arch: ${{ inputs.image_arch }}

    - name: Run Publish Container
      uses: ./.github/promci/actions/publish_mian_images
      if: inputs.quay_io_organization != '' && inputs.quay_io_login != ''
      with:
        registry: quay.io
        organization: ${{ inputs.quay_io_organization }}
        login: ${{ inputs.quay_io_login }}
        password: ${{ inputs.quay_io_password }}
        container_image_name: ${{ inputs.image_name }}
        container_image_arch: ${{ inputs.image_arch }}
