---
name: Save artifacts
inputs:
  directory:
    type: string
    description: Path of the directory to save
runs:
  using: composite
  steps:

    - name: Tar artifacts
      env:
        DIRECTORY: ${{ inputs.directory }}
      run: |
        set -euo pipefail
        uuid="$(cat /proc/sys/kernel/random/uuid | tr -d '-')"
        tar_name="artifact-${uuid}.tar"
        tar cvf "$tar_name" "$DIRECTORY"
        echo "NAME=$tar_name" >> "$GITHUB_OUTPUT"
      shell: bash
      id: tar

    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ steps.tar.outputs.NAME }}
        path: artifact-*.tar
